language: scala

env:
 - SCALISMO_PLATFORM=linux64

jdk:
  - openjdk8

scala:
  - 2.13.2

script:
  - travis_wait sbt ++$TRAVIS_SCALA_VERSION update
  - sbt ++$TRAVIS_SCALA_VERSION -Djava.awt.headless=true compile test
